name: Add issues to planning project

on:
  issues:
    type: opened

jobs:
  add-to-project:
    name: Add issue to planning project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@1.0.2
        with:
          project-url: https://github.com/orgs/teamsbc/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
